export class Controls {
  constructor(element,settings){this.element=element;this.settings=settings;this.move={x:0,y:0};this.look={x:0,y:0};this.fire=this.jump=this.dash=false;this.keys={};this.mobile=matchMedia('(pointer:coarse)').matches;this.bindKeyboard();this.bindPointer();this.bindTouchControls()}
  bindKeyboard(){addEventListener('keydown',event=>{this.keys[event.code]=true;if(event.code==='KeyR')this.reload?.();if(/^Digit[123]$/.test(event.code))this.switchWeapon?.(Number(event.code.at(-1))-1)});addEventListener('keyup',event=>this.keys[event.code]=false)}
  bindPointer(){this.element.addEventListener('click',()=>{if(!this.mobile)this.element.requestPointerLock()});addEventListener('mousemove',event=>{if(document.pointerLockElement===this.element){const scale=.001+this.settings.sensitivity*.00002;this.look.x+=event.movementX*scale;this.look.y+=event.movementY*scale}});addEventListener('mousedown',()=>this.fire=true);addEventListener('mouseup',()=>this.fire=false)}
  bindTouchControls(){const stick=document.getElementById('stick'),knob=stick.querySelector('i');let stickId=null;stick.onpointerdown=event=>{event.preventDefault();stickId=event.pointerId;stick.setPointerCapture(stickId)};stick.onpointermove=event=>{if(event.pointerId!==stickId)return;const rect=stick.getBoundingClientRect(),x=event.clientX-rect.left-rect.width/2,y=event.clientY-rect.top-rect.height/2,length=Math.hypot(x,y),ratio=Math.min(48,length)/(length||1);this.move={x:x/48*ratio,y:-y/48*ratio};knob.style.transform=`translate(${x*ratio}px,${y*ratio}px)`};stick.onpointerup=stick.onpointercancel=()=>{stickId=null;this.move={x:0,y:0};knob.style.transform=''};
    const look=document.getElementById('look');let lookId=null,lastX=0,lastY=0;look.onpointerdown=event=>{lookId=event.pointerId;lastX=event.clientX;lastY=event.clientY;look.setPointerCapture(lookId)};look.onpointermove=event=>{if(event.pointerId!==lookId)return;const scale=.0013+this.settings.sensitivity*.000018;this.look.x+=(event.clientX-lastX)*scale;this.look.y+=(event.clientY-lastY)*scale;lastX=event.clientX;lastY=event.clientY};look.onpointerup=look.onpointercancel=()=>lookId=null;
    ['fire','jump','dash'].forEach(property=>{const button=document.getElementById(property);button.onpointerdown=event=>{event.preventDefault();event.stopPropagation();button.setPointerCapture(event.pointerId);this[property]=true};button.onpointerup=button.onpointercancel=event=>{event.stopPropagation();this[property]=false}})
  }
  sample(){const x=this.move.x+(this.keys.KeyD?1:0)-(this.keys.KeyA?1:0),y=this.move.y+(this.keys.KeyW?1:0)-(this.keys.KeyS?1:0);return{x,y,jump:this.jump||this.keys.Space,dash:this.dash||this.keys.ShiftLeft,fire:this.fire}}
}
