import * as THREE from 'three';
export class Enemy {
  constructor(scene,colliders,obstacles,effects,audio){this.scene=scene;this.colliders=colliders;this.obstacles=obstacles;this.effects=effects;this.audio=audio;this.ray=new THREE.Raycaster();this.group=this.createModel();scene.add(this.group);this.onDeath=null;this.gameEnded=false;this.respawn(new THREE.Vector3())}
  createModel(){const group=new THREE.Group(),material=new THREE.MeshLambertMaterial({color:0xff782e,flatShading:true,emissive:0x000000});const part=(geometry,x,y,z)=>{const mesh=new THREE.Mesh(geometry,material);mesh.position.set(x,y,z);mesh.castShadow=true;group.add(mesh)};part(new THREE.BoxGeometry(1.5,1.5,1),0,1.8,0);part(new THREE.BoxGeometry(1.1,1,1),0,3,0);part(new THREE.CylinderGeometry(.28,.28,1.5,6),-.65,.75,0);part(new THREE.CylinderGeometry(.28,.28,1.5,6),.65,.75,0);part(new THREE.BoxGeometry(.35,.35,.3),-.25,3.1,-.5);part(new THREE.BoxGeometry(.35,.35,.3),.25,3.1,-.5);return group}
  configure(config,pickups){this.config=config;this.pickups=pickups;this.maxHp=config.enemyHp;this.hp=this.maxHp}
  canSeePlayer(player){const origin=this.group.position.clone().add(new THREE.Vector3(0,2,0)),target=player.position.clone(),direction=target.sub(origin),distance=direction.length();this.ray.set(origin,direction.normalize());const blocker=this.ray.intersectObjects(this.obstacles,false)[0];return !blocker||blocker.distance>distance}
  safeMove(direction,distance){const previous=this.group.position.clone();this.group.position.addScaledVector(direction,distance);const box=new THREE.Box3().setFromCenterAndSize(new THREE.Vector3(this.group.position.x,1.4,this.group.position.z),new THREE.Vector3(1.4,2.8,1.4));if(Math.abs(this.group.position.x)>19||Math.abs(this.group.position.z)>19||this.colliders.some(c=>c.intersectsBox(box))){this.group.position.copy(previous);const side=new THREE.Vector3(-direction.z,0,direction.x);this.group.position.addScaledVector(side,distance);return false}return true}
  update(dt,player,onShot){if(!this.alive)return;this.thinkTimer-=dt;this.shotTimer-=dt;this.group.position.y=Math.max(0,this.group.position.y-8*dt);const toPlayer=player.position.clone().sub(this.group.position),distance=toPlayer.length(),visible=this.canSeePlayer(player);this.group.lookAt(player.position.x,this.group.position.y,player.position.z);if(this.thinkTimer>0)return;this.thinkTimer=.16;let direction=toPlayer.normalize(),speed=this.config.enemySpeed,goal='fight';const health=this.pickups?.nearestHealth(this.group.position);if(this.hp<=this.maxHp*.3&&health){direction=health.position.clone().sub(this.group.position).setY(0).normalize();goal='heal'}else if(this.hp<=this.maxHp*.3){direction.negate();goal='retreat'}else if(distance>11)goal='approach';else if(distance<7){direction.negate();goal='retreat'}else{direction.set(-direction.z,0,direction.x).multiplyScalar(this.strafeDirection)}if(!visible&&goal==='fight')goal='approach';this.safeMove(direction,speed*.16*(goal==='retreat'?1.2:1));if(Math.random()<this.config.jump*.16&&this.group.position.y===0)this.group.position.y=.8;if(Math.random()<this.config.dash*.16)this.safeMove(direction,1.1);
    if(visible&&distance<25&&this.shotTimer<=0){if(this.burstShots>=3){this.shotTimer=1.3;this.burstShots=0;this.strafeDirection*=-1;return}this.shotTimer=this.config.reaction;this.burstShots++;this.seenTime+=.16;if(this.seenTime>this.config.reaction&&Math.random()<this.config.accuracy)onShot(this.config.attack);else onShot(0)}else if(!visible)this.seenTime=0}
  damage(amount){if(!this.alive)return;this.hp-=amount;const material=this.group.children[0].material;material.emissive.set(0x88ffff);setTimeout(()=>material.emissive.set(0),90);if(this.hp<=0)this.die()}
  die(){if(!this.alive)return;this.alive=false;const material=this.group.children[0].material;material.emissive.set(0xffffff);setTimeout(()=>{this.group.visible=false;this.effects.burst(this.group.position.clone().add(new THREE.Vector3(0,1.5,0)),0xff8a31,18,.22,.9)},100);this.audio.play('kill');this.onDeath?.();setTimeout(()=>{if(!this.gameEnded)this.respawn(this.lastPlayerPosition||new THREE.Vector3())},2000)}
  respawn(playerPosition){const candidates=[[-16,-15],[16,-15],[-16,15],[16,15],[0,-16]];const safe=candidates.map(([x,z])=>new THREE.Vector3(x,0,z)).sort((a,b)=>b.distanceToSquared(playerPosition)-a.distanceToSquared(playerPosition))[0];this.group.position.copy(safe);this.group.visible=true;this.group.children[0].material.emissive.set(0);this.hp=this.maxHp||100;this.alive=true;this.thinkTimer=1;this.shotTimer=1.2;this.seenTime=0;this.burstShots=0;this.strafeDirection=Math.random()<.5?-1:1;this.effects?.ring(safe,0x7eeeff)}
}
