import * as THREE from 'three';
import {createArena} from './arena.js';import {Controls} from './controls.js';import {Player} from './player.js';import {Weapon} from './weapon.js';import {Enemy} from './enemy.js';import {UI} from './ui.js';import {Effects} from './effects.js';import {Pickups} from './pickups.js';import {SupportDrone} from './supportDrone.js';import {DIFFICULTIES,loadDifficulty} from './difficulty.js';import {loadSettings,applySettings,bindSettings} from './settings.js';import {GameAudio} from './audio.js';

const settings=loadSettings();applySettings(settings);const audio=new GameAudio(settings),scene=new THREE.Scene();scene.background=new THREE.Color(0x1b2445);scene.fog=new THREE.Fog(0x1b2445,36,66);const camera=new THREE.PerspectiveCamera(78,innerWidth/innerHeight,.1,100),renderer=new THREE.WebGLRenderer({antialias:settings.quality!=='low',powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,settings.quality==='high'?2:1.25));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=settings.quality!=='low';document.getElementById('game').append(renderer.domElement);
const colliders=[],obstacles=createArena(scene,colliders),effects=new Effects(scene,settings.quality),controls=new Controls(renderer.domElement,settings),player=new Player(camera,colliders,effects,audio),weapon=new Weapon(scene,camera,effects,audio),enemy=new Enemy(scene,colliders,obstacles,effects,audio),ui=new UI(camera),pickups=new Pickups(scene,effects,audio),drone=new SupportDrone(scene,effects,audio),clock=new THREE.Clock();scene.add(camera);
let running=false,kills=0,deaths=0,deathStreak=0,killsSinceDrone=0,invulnerable=false,relax=false,difficultyKey=loadDifficulty(),config=DIFFICULTIES[difficultyKey];

function selectDifficulty(value){difficultyKey=value;config=DIFFICULTIES[value];localStorage.setItem('firstBlastDifficulty',value);document.querySelectorAll('#difficulty button').forEach(button=>button.classList.toggle('selected',button.dataset.value===value))}
document.querySelectorAll('#difficulty button').forEach(button=>button.onclick=()=>selectDifficulty(button.dataset.value));selectDifficulty(difficultyKey);bindSettings(settings,()=>{audio.settings=settings});document.getElementById('settingsButton').onclick=()=>document.getElementById('settings').classList.remove('hidden');document.getElementById('closeSettings').onclick=()=>document.getElementById('settings').classList.add('hidden');
function switchWeapon(index){weapon.switch(index);ui.selectWeapon(index)}controls.switchWeapon=switchWeapon;controls.reload=()=>weapon.reload();document.querySelectorAll('#weaponSlots button').forEach(button=>button.onclick=event=>{event.stopPropagation();switchWeapon(Number(button.dataset.weapon))});

enemy.onDeath=()=>{kills++;deathStreak=0;killsSinceDrone++;ui.marker(true);if(drone.active&&killsSinceDrone>=2)drone.hide();if(kills>=5&&!relax)finish(true)};
function hurt(amount){if(!amount||invulnerable||!running)return;player.takeDamage(relax?amount*.25:amount);if(player.hp>0)return;deaths++;deathStreak++;invulnerable=true;if(deathStreak>=3)drone.show(player);if(deaths>=5&&!relax)return finish(false);player.respawn();effects.ring(player.position,0x76eeff);document.body.animate([{filter:'brightness(2)'},{filter:'brightness(1)'}],450);setTimeout(()=>invulnerable=false,1200)}
function finish(win){running=false;enemy.gameEnded=true;audio.play(win?'victory':'defeat');ui.end(win,kills,deaths)}
function start(){audio.unlock();relax=document.getElementById('relax').checked;config=relax?{...DIFFICULTIES.easy,attack:4,accuracy:.12,enemySpeed:1.7,assist:1}:DIFFICULTIES[difficultyKey];kills=deaths=deathStreak=killsSinceDrone=0;running=true;invulnerable=false;enemy.gameEnded=false;player.configure(config.playerHp);player.respawn();enemy.configure(config,pickups);enemy.respawn(player.position);weapon.relax=relax;weapon.refillAll();effects.ring(player.position);document.getElementById('start').classList.add('hidden');document.getElementById('message').classList.add('hidden');document.getElementById('hud').classList.remove('hidden');if(relax)drone.show(player);else drone.hide();if(!controls.mobile)renderer.domElement.requestPointerLock()}
document.getElementById('startButton').onclick=start;document.getElementById('again').onclick=start;
function aimAssist(){if(settings.aimAssist==='off'||!enemy.alive)return{x:0,y:0,strength:0};const projected=enemy.group.position.clone().add(new THREE.Vector3(0,2,0)).project(camera);if(projected.z>1||Math.abs(projected.x)>.3||Math.abs(projected.y)>.3)return{x:0,y:0,strength:0};const levels={weak:.2,normal:.45,strong:.75},strength=(levels[settings.aimAssist]||0)*config.assist*(controls.mobile?1.25:1);return{x:-projected.x*strength,y:projected.y*strength,strength}}
function loop(){requestAnimationFrame(loop);const dt=Math.min(clock.getDelta(),.04);if(running){const input=controls.sample();player.update(dt,input,controls.look,aimAssist());weapon.update(dt,input.fire,enemy,obstacles,(damage,kill)=>ui.damage(damage,enemy.group.position,kill));enemy.lastPlayerPosition=player.position.clone();enemy.update(dt,player,hurt);pickups.update(dt,player,weapon,enemy);drone.update(dt,player,enemy);effects.update(dt);if(relax)player.hp=Math.min(player.maxHp,player.hp+dt*4);ui.update(player,weapon,kills,deaths)}renderer.render(scene,camera)}loop();
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);weapon.layout()});addEventListener('contextmenu',event=>event.preventDefault());
