import * as THREE from 'three';
export class Player {
  constructor(camera,colliders,effects,audio){this.camera=camera;this.colliders=colliders;this.effects=effects;this.audio=audio;this.position=new THREE.Vector3(0,1.7,16);this.velocity=new THREE.Vector3();this.yaw=this.pitch=0;this.maxHp=this.hp=200;this.grounded=true;this.dashReady=true;this.shieldUntil=this.speedUntil=0;camera.position.copy(this.position)}
  configure(maxHp){this.maxHp=maxHp;this.hp=maxHp}
  update(dt,input,look,aim={x:0,y:0,strength:0}){this.yaw-=look.x*(1-aim.strength*.35)+aim.x*dt;this.pitch=Math.max(-1.35,Math.min(1.35,this.pitch-look.y*(1-aim.strength*.35)+aim.y*dt));look.x=look.y=0;this.camera.rotation.set(this.pitch,this.yaw,0,'YXZ');const forward=new THREE.Vector3(-Math.sin(this.yaw),0,-Math.cos(this.yaw)),right=new THREE.Vector3(Math.cos(this.yaw),0,-Math.sin(this.yaw)),wish=forward.multiplyScalar(input.y).add(right.multiplyScalar(input.x));if(wish.length()>1)wish.normalize();let speed=performance.now()<this.speedUntil?8.7:7;if(input.dash&&this.dashReady){speed*=2.5;this.dashReady=false;this.audio.play('dash');this.effects.burst(this.position,0x8feaff,4,.12,.25);setTimeout(()=>this.dashReady=true,1000)}this.velocity.x=wish.x*speed;this.velocity.z=wish.z*speed;if(input.jump&&this.grounded){this.velocity.y=8.5;this.grounded=false;this.audio.play('jump');this.effects.burst(this.position.clone().setY(.2),0xd8c9a5,4,.18,.3)}this.velocity.y-=22*dt;this.moveAxis('x',this.velocity.x*dt);this.moveAxis('z',this.velocity.z*dt);this.position.y+=this.velocity.y*dt;if(this.position.y<=1.7){this.position.y=1.7;this.velocity.y=0;this.grounded=true}if((Math.abs(this.position.x+12)<2.5&&Math.abs(this.position.z-1)<2.5)||(Math.abs(this.position.x-10)<2.5&&Math.abs(this.position.z+1)<2.5)||(Math.abs(this.position.x)<2.5&&Math.abs(this.position.z+18)<2.5)){if(this.grounded)this.velocity.y=12}this.camera.position.copy(this.position)}
  moveAxis(axis,distance){this.position[axis]+=distance;const box=new THREE.Box3().setFromCenterAndSize(new THREE.Vector3(this.position.x,this.position.y-.8,this.position.z),new THREE.Vector3(1,1.8,1));if(this.colliders.some(collider=>collider.intersectsBox(box)))this.position[axis]-=distance}
  takeDamage(amount){const reduced=performance.now()<this.shieldUntil?amount*.45:amount;this.hp-=reduced;return reduced}
  respawn(){this.position.set(0,1.7,16);this.velocity.set(0,0,0);this.hp=this.maxHp;this.shieldUntil=this.speedUntil=0}
}
