import * as THREE from 'three';
export class UI {
  constructor(camera){this.camera=camera;this.hp=document.getElementById('hpBar');this.hpText=document.getElementById('hpText');this.ammo=document.getElementById('ammo');this.reload=document.getElementById('reloadText');this.crosshair=document.getElementById('crosshair');this.damageLayer=document.getElementById('damageNumbers');this.markerTimer=0}
  update(player,weapon,kills,deaths){this.hp.style.width=`${Math.max(0,player.hp/player.maxHp*100)}%`;this.hp.style.background=player.hp<player.maxHp*.3?'#ff3b4e':'';this.hpText.textContent=Math.ceil(player.hp);this.ammo.textContent=weapon.currentAmmo;this.reload.textContent=weapon.reloading?'RELOADING...':'';document.getElementById('weaponName').textContent=weapon.definition.name;document.getElementById('kills').textContent=kills;document.getElementById('deaths').textContent=deaths;document.getElementById('buffs').textContent=[performance.now()<player.shieldUntil?'🛡 シールド':'',performance.now()<player.speedUntil?'⚡ スピード':''].filter(Boolean).join('　')}
  selectWeapon(index){document.querySelectorAll('#weaponSlots button').forEach((button,i)=>button.classList.toggle('selected',i===index));document.querySelector('.ammo').animate([{transform:'translateY(8px)',opacity:.4},{transform:'none',opacity:1}],180)}
  marker(kill=false){clearTimeout(this.markerTimer);this.crosshair.classList.remove('hit','kill');void this.crosshair.offsetWidth;this.crosshair.classList.add(kill?'kill':'hit');this.markerTimer=setTimeout(()=>this.crosshair.classList.remove('hit','kill'),150)}
  damage(amount,position,kill=false){const vector=position.clone().add(new THREE.Vector3(0,3,0)).project(this.camera);const element=document.createElement('div');element.className=`damage-number ${amount>=35?'big':''} ${kill?'kill':''}`;element.textContent=kill?`撃破! ${amount}`:amount;element.style.left=`${(vector.x*.5+.5)*innerWidth}px`;element.style.top=`${(-vector.y*.5+.5)*innerHeight}px`;this.damageLayer.append(element);setTimeout(()=>element.remove(),850);this.marker(kill)}
  end(win,kills,deaths){document.exitPointerLock?.();document.getElementById('result').textContent=win?'Victory!':'Game Over';document.getElementById('resultDetail').textContent=`撃破 ${kills}　/　敗北 ${deaths}`;document.getElementById('message').classList.remove('hidden')}
}
