import * as THREE from 'three';
const WEAPONS=[
  {name:'PULSE BLASTER',ammo:20,damage:20,rate:.12,color:0xaaffff,sound:'pulse'},
  {name:'SPARK SHOT',ammo:6,damage:12,rate:.7,color:0xffb42d,sound:'spark',pellets:6,spread:.075},
  {name:'BUBBLE LAUNCHER',ammo:4,damage:42,rate:.85,color:0xa56eff,sound:'bubble',projectile:true},
];

export class Weapon {
  constructor(scene,camera,effects,audio){this.scene=scene;this.camera=camera;this.effects=effects;this.audio=audio;this.index=0;this.ammo=WEAPONS.map(w=>w.ammo);this.cooldown=0;this.reloading=false;this.relax=false;this.ray=new THREE.Raycaster();this.models=this.createModels();this.projectiles=Array.from({length:6},()=>this.createProjectile());this.switch(0,true)}
  get definition(){return WEAPONS[this.index]}get currentAmmo(){return this.relax?'∞':this.ammo[this.index]}
  createModels(){return WEAPONS.map((weapon,index)=>{const group=new THREE.Group(),material=new THREE.MeshLambertMaterial({color:weapon.color,emissive:weapon.color,emissiveIntensity:.12});const body=new THREE.Mesh(index===2?new THREE.CylinderGeometry(.24,.4,1.2,8):new THREE.BoxGeometry(index===1?.65:.42,.38,index===1?1.05:1.35),material);body.rotation.x=Math.PI/2;group.add(body);if(index===1){for(let x of[-.22,0,.22]){const barrel=new THREE.Mesh(new THREE.CylinderGeometry(.06,.08,.65,6),material);barrel.rotation.x=Math.PI/2;barrel.position.set(x,.03,-.65);group.add(barrel)}}else{const barrel=new THREE.Mesh(new THREE.CylinderGeometry(index===2?.22:.1,index===2?.26:.14,.7,8),material);barrel.rotation.x=Math.PI/2;barrel.position.z=-.75;group.add(barrel)}group.position.set(.55,-.48,-1);group.rotation.y=-.12;this.camera.add(group);group.visible=false;return group})}
  createProjectile(){const mesh=new THREE.Mesh(new THREE.SphereGeometry(.28,8,6),new THREE.MeshBasicMaterial({color:0xb78aff,transparent:true,opacity:.85}));mesh.visible=false;this.scene.add(mesh);return{mesh,active:false,velocity:new THREE.Vector3(),life:0}}
  switch(index,silent=false){if(!WEAPONS[index]||this.index===index&&!silent)return;this.models.forEach(model=>model.visible=false);this.index=index;this.models[index].visible=true;this.models[index].position.y=-.8;this.reloading=false;if(!silent)this.audio.play('switch')}
  refill(){this.ammo[this.index]=this.definition.ammo}
  refillAll(){this.ammo=WEAPONS.map(weapon=>weapon.ammo)}
  reload(){if(this.relax||this.reloading||this.ammo[this.index]===this.definition.ammo)return;this.reloading=true;this.audio.play('reload');setTimeout(()=>{this.ammo[this.index]=this.definition.ammo;this.reloading=false},1300)}
  update(dt,fire,enemy,obstacles,onDamage){this.cooldown-=dt;const model=this.models[this.index];model.position.y+=(-.48-model.position.y)*Math.min(1,dt*(this.reloading?2:10));model.position.z+=(-1-model.position.z)*Math.min(1,dt*14);if(this.reloading)model.position.y=-.7;this.updateProjectiles(dt,enemy,obstacles,onDamage);if(!fire||this.cooldown>0||this.reloading)return;if(!this.relax&&this.ammo[this.index]<=0){this.reload();return}if(!this.relax)this.ammo[this.index]--;this.cooldown=this.definition.rate;this.audio.play(this.definition.sound);model.position.z=-.82;if(this.definition.projectile)this.fireBubble();else this.fireHitscan(enemy,obstacles,onDamage)}
  fireHitscan(enemy,obstacles,onDamage){const count=this.definition.pellets||1;let total=0,hitPoint=null;for(let i=0;i<count;i++){const offset=new THREE.Vector2((Math.random()-.5)*(this.definition.spread||0),(Math.random()-.5)*(this.definition.spread||0));this.ray.setFromCamera(offset,this.camera);const enemyHit=enemy.alive?this.ray.intersectObject(enemy.group,true)[0]:null,wallHit=this.ray.intersectObjects(obstacles,false)[0];const end=(enemyHit&&(!wallHit||enemyHit.distance<wallHit.distance)?enemyHit:wallHit)?.point||this.ray.ray.at(30,new THREE.Vector3());this.effects.tracer(this.camera.position.clone(),end,this.definition.color);if(enemyHit&&(!wallHit||enemyHit.distance<wallHit.distance)){const falloff=this.index===1?Math.max(.3,1-enemyHit.distance/24):1;total+=this.definition.damage*falloff;hitPoint=enemyHit.point}else if(wallHit)this.effects.burst(wallHit.point,this.definition.color,2,.08,.2)}if(total){enemy.damage(Math.round(total));this.effects.burst(hitPoint,this.definition.color,4,.1,.3);this.audio.play('hit');onDamage(Math.round(total),enemy.hp<=0)}}
  fireBubble(){const shot=this.projectiles.find(p=>!p.active);if(!shot)return;shot.active=true;shot.life=3.5;shot.damage=this.definition.damage;shot.mesh.visible=true;shot.mesh.position.copy(this.camera.position).add(new THREE.Vector3(0,-.12,-.8).applyQuaternion(this.camera.quaternion));shot.velocity.set(0,0,-10).applyQuaternion(this.camera.quaternion);this.effects.burst(shot.mesh.position,0xa56eff,4,.12,.25)}
  updateProjectiles(dt,enemy,obstacles,onDamage){for(const shot of this.projectiles){if(!shot.active)continue;shot.life-=dt;shot.mesh.position.addScaledVector(shot.velocity,dt);const enemyCenter=enemy.group.position.clone().setY(1.6),hitEnemy=enemy.alive&&shot.mesh.position.distanceTo(enemyCenter)<1.6;const hitWall=obstacles.some(object=>(object.userData.collisionBox||(object.userData.collisionBox=new THREE.Box3().setFromObject(object))).distanceToPoint(shot.mesh.position)<.2);if(hitEnemy||hitWall||shot.life<=0){let damage=0;if(enemy.alive){const distance=shot.mesh.position.distanceTo(enemyCenter);damage=Math.max(0,Math.round(shot.damage*(1-distance/5)));if(damage){enemy.damage(damage);onDamage(damage,enemy.hp<=0)}}this.effects.burst(shot.mesh.position,0xa56eff,12,.25,.55);shot.active=false;shot.mesh.visible=false}}}
}
export {WEAPONS};
